### ISSUE TITLE
docs: compatibility with bun/deno?

### ISSUE THREAD

**Issue by benmccann** [privatenumber/get-conditions#1]
### Feature request

Mention if this approach works with bun/deno

### Motivations

I want to know how widely supported this library is and if using it would break compatibility with some platforms

### Additional context

It does look like it works with bun: https://bun.sh/docs/runtime/modules

I wasn't able to find from a quick search if it works with Deno or not though

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
I developed it with Node in mind so I haven't tested other runtimes, but I'm happy to accept PRs that add support!

**Comment by benmccann** [comment]
@bartlomieju do you know if this works in Deno or how one might get/set conditions in Deno? We're trying to address an issue in the upcoming Vite 6 release potentially using this library or a similar approach and want to make sure we don't break Deno

**Comment by bartlomieju** [comment]
Hey @benmccann - we do support conditional exports, but we don't accept a flag to set them (at least at the moment). There is a fixed list of conditions that Deno evaluates that I can provide you if you want.

**Comment by benmccann** [comment]
Thanks @bartlomieju! The one I'm particularly interested in is whether you have a way to set `development` vs `production` as a condition and what might control which one is set.

**Comment by bartlomieju** [comment]
@benmccann currently we don't support either of them and there's no way to set conditions via CLI flag like it's available in Node. If this is something that you really need we'll consider implementing it in the near future.

**Comment by benmccann** [comment]
Thanks. No need at the moment as we're investigating solutions for our issue, but I'll let you know if that changes

**Comment by privatenumber** [comment]
Thanks for the detailed discussion.

While I appreciate the interesting topic and enthusiasm, I feel this conversation has drifted from actionable improvements specific to this project. For future discussions, I recommend moving such discussions to the appropriate repository to for better visibility and relevance.

I'm going to close this issue as Deno currently does not support passing in conditions, which limits compatibility. I haven't tested with Bun, but given [it supports the same flag](https://bun.sh/docs/runtime/modules#custom-conditions), it should probably work.

Again, feel free to open a PR if there's interest in improving docs or compatibility further.
